# Generated by Django 3.2.7 on 2022-02-07 16:31

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TescoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_tokens', picklefield.fields.PickledObjectField(editable=False)),
                ('products_data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
