# Generated by Django 3.2.7 on 2022-02-13 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets_data', '0003_amazondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazondata',
            name='products_entities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
