# Generated by Django 3.2.7 on 2022-02-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproduct',
            name='short_name',
        ),
    ]
