# Generated by Django 3.2.7 on 2022-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesco_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tescoproduct',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
