# Generated by Django 3.2.7 on 2022-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date_created',
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last_updated'),
        ),
    ]
