# Generated by Django 3.2.7 on 2022-02-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220211_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='products_amazon',
            new_name='products_british_online_supermarket',
        ),
    ]
