# Generated by Django 3.2.7 on 2022-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SainsburysProduct',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('1', '$'), ('2', '€'), ('3', '£')], max_length=20)),
                ('full_name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=2000)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
        ),
    ]
